#!/bin/sh /etc/rc.common
. /lib/ar71xx.sh

START=99

bccmd_init_csr8x11() {
  hciconfig hci0 up
  bccmd -t hci -d hci0 psload /etc/bluetooth/csr8x11-a12-bt4.2-patch.psr
  bccmd -t hci -d hci0 psload /etc/bluetooth/csr8x11-coex.psr
  bccmd -t hci -d hci0 warmreset
}

start() {
  board_name=$(ar71xx_board_name)

  case "$board_name" in
  cus531mp3|\
  cus531mp3-dual|\
  cus531mp3-nand)
    bccmd_init_csr8x11
    ;;
  esac
}

